# -*- coding: utf-8 -*-
"""Rabu_2_Februari_Siang.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s7jP0iZlK1XgsIs5dNz_43X3dwjvGY6s

Nomor 1
"""

def divisible (m,n):
    if (m % n == 0):
        return True

    else :
        return False

print(divisible(60,12))
print(divisible(45,7))

"""Nomor 2"""

def main_menu():
    print("Welcome To Sunshine Cafe")
    print('-'*20)
    print('-'*10, "MAIN MENU",'-'*10)
    print(" 1. Onion Ring ")
    print(" 2. Chicken Fingers ")
    print(" 3. Potato Wedges ")
    print('-'*20)
    number = input(" What number do you want to order? ")
    if number == '1':
        print('a portion of Onion Rings coming soon!')
    elif number == '2':
        print('a portion of Chicken Fingers coming soon!')
    elif number == '3':
        print('a portion of Potato Wedges coming soon!')
    else :
        print('sorry, this menu is not available')
# main program
if __name__=='__main__':
    main_menu()

"""Nomor 3

"""

def rand_divis_3 ():
    x=int(input("Masukkan bilangan: "))
    
    if (x % 3 == 0):
        return True

    else :
        return False
print(rand_divis_3())

"""Nomor 4"""

1 != 1

def not_equal(x,y):
    if (x != y):
        return True
    else :
        return False
print(not_equal(7,3))

def not_equal(x,y):
    if (not (x == y)):
        return True
    else :
        return False
print(not_equal(7,3))

"""Nomor 5"""

def ask_name():
    name = input("Enter your name: ")

ask_name()
print("Your name is", name)

name = input ("Enter your name:")
print ("You your name is :", name)